version: 0.0
os: linux
files:
  - source: subtitledownloader-1.0-SNAPSHOT.jar
    destination: /opt/tomcat/webapps

hooks:
  AfterInstall:
    - location: /opt/tomcat/webapps/start_server.sh
      timeout: 900
      runas: root
  ApplicationStop:
    - location: /opt/tomcat/webapps/stop_server.sh
      timeout: 300  
      runas: root
  ApplicationStart:
    - location: /opt/tomcat/webapps/verify_service.sh
      timeout: 300
      runas: root

